// Complete mock datasets mirroring Linux/Rust v6 runtime & macOS presentation parity

export const mockConfig = {
  schemaVersion: 6,
  listener: {
    host: '127.0.0.1',
    port: 57878,
    allowedCIDRs: ['127.0.0.1/32', '192.168.1.0/24'],
  },
  endpoints: [
        {
          id: 'ep-anthropic-direct',
          name: 'Anthropic 官方直连',
          baseURL: 'https://api.anthropic.com',
          protocol: 'anthropic',
          priority: 0,
          timeoutSeconds: 60,
          streamIdleTimeoutSeconds: 30,
          pinnedIPs: [],
          pinnedIPExclusive: false,
          stickyGroup: 'anthropic-direct',
          keepAlive: true,
          catalog: {
            models: ['claude-3-7-sonnet-20250219', 'claude-3-5-sonnet-20241022'],
            source: 'https://api.anthropic.com/v1/models',
            status: '已获取',
            error: '',
            updatedAt: '1720000000',
          },
          enabled: true,
          modelMappings: [
            {
              from: 'claude-3-7-sonnet-latest', to: 'claude-3-7-sonnet-20250219',
              thinking: 'adaptive', context: 'oneMillion',
            },
            {
              from: 'claude-3-5-sonnet-latest', to: 'claude-3-5-sonnet-20241022',
              thinking: 'passThrough', context: 'passThrough', failoverTimeoutSeconds: 8,
            },
          ],
        },
        {
          id: 'ep-openrouter-fast',
          name: 'OpenRouter 聚合加速',
          baseURL: 'https://openrouter.ai/api/v1',
          protocol: 'auto',
          priority: 1,
          timeoutSeconds: 45,
          streamIdleTimeoutSeconds: 20,
          pinnedIPs: ['104.18.2.161', '104.18.3.161'],
          pinnedIPExclusive: true,
          stickyGroup: 'openrouter-fast',
          keepAlive: true,
          catalog: {
            models: ['openai/gpt-4o', 'anthropic/claude-3.7-sonnet'],
            source: 'https://openrouter.ai/api/v1/models',
            status: '已获取',
            error: '',
            updatedAt: '1720000000',
          },
          enabled: true,
          modelMappings: [
            {
              from: 'claude-3-7-sonnet', to: 'anthropic/claude-3.7-sonnet',
              thinking: 'passThrough', context: 'oneMillion', failoverTimeoutSeconds: 5,
            },
            {
              from: 'claude-3-5-haiku', to: 'anthropic/claude-3.5-haiku',
              thinking: 'disable', context: 'passThrough',
            },
          ],
        },
        {
          id: 'ep-azure-eastus',
          name: 'Azure OpenAI 通道',
          baseURL: 'https://eastus.openai.azure.com/openai/deployments',
          protocol: 'openai',
          priority: 10,
          timeoutSeconds: 30,
          streamIdleTimeoutSeconds: 15,
          pinnedIPs: ['20.185.12.8'],
          pinnedIPExclusive: false,
          stickyGroup: 'azure-eastus',
          keepAlive: true,
          catalog: {
            models: ['gpt-4o', 'gpt-4o-mini'],
            source: 'https://eastus.openai.azure.com/openai/deployments/v1/models',
            status: '已获取',
            error: '',
            updatedAt: '1720000000',
          },
          enabled: true,
          modelMappings: [
            {
              from: 'claude-3-7-sonnet', to: 'gpt-4o',
              thinking: 'passThrough', context: 'oneMillion', failoverTimeoutSeconds: 7.5,
            },
            {
              from: 'claude-3-5-haiku', to: 'gpt-4o-mini',
              thinking: 'disable', context: 'passThrough',
            },
          ],
        },
        {
          id: 'ep-deepseek-backup',
          name: 'DeepSeek 应急通道',
          baseURL: 'https://api.deepseek.com/v1',
          protocol: 'openai',
          priority: 11,
          timeoutSeconds: 25,
          streamIdleTimeoutSeconds: 10,
          pinnedIPs: [],
          pinnedIPExclusive: false,
          stickyGroup: 'deepseek-emergency',
          keepAlive: false,
          catalog: {
            models: [],
            source: '',
            status: '未获取',
            error: '',
            updatedAt: '',
          },
          enabled: true,
          modelMappings: [
            { from: 'claude-3-7-sonnet', to: 'deepseek-chat' },
          ],
        },
  ],
  featureRules: [
    {
      id: 'rule-websearch',
      name: 'WebSearch 搜索智能劫持',
      enabled: true,
      match: {
        requestKind: 'websearch',
        toolTypePrefix: 'web_search',
      },
      target: {
        endpointID: 'ep-openrouter-fast',
        model: 'gpt-4o-mini',
        protocol: 'openai',
      },
    },
    {
      id: 'rule-webfetch',
      name: 'WebFetch 网页抓取分流',
      enabled: true,
      match: {
        requestKind: 'webfetch',
      },
      target: {
        endpointID: 'ep-openrouter-fast',
        model: 'gpt-4o-mini',
        protocol: 'openai',
      },
    },
    {
      id: 'rule-classifier',
      name: '安全分类器分流',
      enabled: true,
      match: {
        requestKind: 'classifier',
      },
      target: {
        model: 'gpt-4o-mini',
      },
    },
  ],
  retry: {
    responseTimeoutSeconds: 60,
    streamIdleTimeoutSeconds: 30,
    max500Retries: 0,
    failoverOn500: true,
    retryDelaySeconds: null,
    passThroughRetryDelay: true,
    sessionStickyRetries: 2,
    maxDeferredRounds: 3,
    crossRoundRetries: 3,
    maxRetryDurationSeconds: 120,
    pinnedIPConcurrency: 3,
  },
};

export const mockSecretStatus = {
  inboundAuthToken: { configured: true, last4: '8899' },
  endpoints: {
    'ep-anthropic-direct': { configured: true, last4: '9a1b' },
    'ep-openrouter-fast': { configured: true, last4: '7c2d' },
    'ep-azure-eastus': { configured: true, last4: '44ef' },
    'ep-deepseek-backup': { configured: true, last4: '109a' },
  },
};

export const mockStatus = {
  running: true,
  runtimeApiVersion: 1,
  version: '0.2.0',
  generation: 'gen-8f921bc3',
  uptimeSeconds: 14280,
  providers: 4,
  endpoints: 4,
  listener: { host: '127.0.0.1', port: 57878 },
  health: {
    state: 'healthy',
    sampleCount: 50,
    successRate: 0.98,
    headline: '代理服务正常响应客户端请求，近期请求成功率 98%',
  },
  lastError: null,
};

const now = Date.now();

export const mockRuntime = {
  // 成功 + 失败 + 取消必须与请求总数守恒；否则前端只能把成功率显示成
  // 一个看似合理但实际失真的数字。真实 API 也以这个口径返回 pending。
  clientRequests: 1287,
  clientSuccesses: 1256,
  clientFailures: 28,
  upstreamAttempts: 1390,
  upstreamSuccesses: 1260,
  upstreamFailures: 130,
  failovers: 42,
  recentEvents: [
    {
      id: 'ev-stream-live-1',
      requestID: 'req-live-001',
      timestamp: now - 3500,
      kind: 'client',
      endpointID: 'ep-anthropic-direct',
      endpointName: 'Anthropic 官方直连',
      upstreamHost: 'api.anthropic.com',
      clientKind: 'claude_code',
      requestPurpose: 'standard',
      clientModel: 'claude-3-7-sonnet-latest',
      effectiveModel: 'claude-3-7-sonnet-20250219',
      upstreamModel: 'claude-3-7-sonnet-20250219',
      statusCode: 200,
      phase: 'inFlight',
      outcome: null,
      ttfbMS: 620,
      durationMS: 3500,
      failover: false,
      toolCalls: ['read_file', 'grep_search'],
      streamTrace: {
        chunkCount: 84,
        bytesReceived: 18420,
        maxChunkGapMS: 120,
        lastChunkAtMS: 3480,
        terminalEvent: null,
      },
      message: '流式持续输出中',
    },
    {
      id: 'ev-stream-live-1-up',
      requestID: 'req-live-001',
      timestamp: now - 3500,
      kind: 'upstream',
      endpointID: 'ep-anthropic-direct',
      endpointName: 'Anthropic 官方直连',
      upstreamHost: 'api.anthropic.com',
      clientKind: 'claude_code',
      requestPurpose: 'standard',
      clientModel: 'claude-3-7-sonnet-latest',
      effectiveModel: 'claude-3-7-sonnet-20250219',
      upstreamModel: 'claude-3-7-sonnet-20250219',
      statusCode: 200,
      phase: 'inFlight',
      outcome: null,
      ttfbMS: 620,
      durationMS: 3500,
      failover: false,
      upstreamRequestID: 'req_01ABC999XYZ',
      message: '上游传输中',
    },
    {
      id: 'ev-failover-client',
      requestID: 'req-failover-002',
      timestamp: now - 38000,
      kind: 'client',
      endpointID: 'ep-azure-eastus',
      endpointName: 'Azure OpenAI 通道',
      upstreamHost: 'eastus.openai.azure.com',
      clientKind: 'claude_code',
      requestPurpose: 'standard',
      clientModel: 'claude-3-7-sonnet',
      effectiveModel: 'gpt-4o',
      upstreamModel: 'gpt-4o',
      statusCode: 200,
      phase: 'completed',
      outcome: 'succeeded',
      ttfbMS: 5800,
      durationMS: 8400,
      failover: true,
      message: 'Anthropic 入口返回 429，已故障转移到 Azure OpenAI 通道并完成请求',
      streamTrace: {
        chunkCount: 142,
        bytesReceived: 38920,
        maxChunkGapMS: 240,
        lastChunkAtMS: 8350,
        terminalEvent: '[DONE]',
        usage: { inputTokens: 8400, outputTokens: 1800 },
      },
    },
    {
      id: 'ev-failover-up2',
      requestID: 'req-failover-002',
      timestamp: now - 38000,
      kind: 'upstream',
      endpointID: 'ep-azure-eastus',
      endpointName: 'Azure OpenAI 通道',
      upstreamHost: 'eastus.openai.azure.com',
      clientKind: 'claude_code',
      requestPurpose: 'standard',
      clientModel: 'claude-3-7-sonnet',
      effectiveModel: 'gpt-4o',
      upstreamModel: 'gpt-4o',
      statusCode: 200,
      phase: 'completed',
      outcome: 'succeeded',
      ttfbMS: 1100,
      durationMS: 3700,
      failover: true,
      upstreamStatusCode: 200,
      upstreamRequestID: 'azure-req-888999',
      message: '故障转移后入口成功返回响应',
    },
    {
      id: 'ev-failover-up1',
      requestID: 'req-failover-002',
      timestamp: now - 42700,
      kind: 'upstream',
      endpointID: 'ep-anthropic-direct',
      endpointName: 'Anthropic 官方直连',
      upstreamHost: 'api.anthropic.com',
      clientKind: 'claude_code',
      requestPurpose: 'standard',
      clientModel: 'claude-3-7-sonnet',
      effectiveModel: 'claude-3-7-sonnet-20250219',
      upstreamModel: 'claude-3-7-sonnet-20250219',
      statusCode: 429,
      phase: 'completed',
      outcome: 'failed',
      ttfbMS: 4700,
      durationMS: 4700,
      failover: false,
      failureKind: 'upstream_http_status',
      failurePhase: 'response_headers',
      upstreamStatusCode: 429,
      upstreamRequestID: 'req_01FAIL429',
      failureDetail: 'HTTP 429 Too Many Requests: Rate limit exceeded for tier 4',
      message: '上游返回 429 速率限制',
    },
    {
      id: 'ev-codex-response-failed-200',
      requestID: 'req-codex-failed-005',
      timestamp: now - 65000,
      kind: 'client',
      endpointID: 'ep-openrouter-fast',
      endpointName: 'OpenRouter 聚合加速',
      upstreamHost: 'openrouter.ai',
      clientKind: 'codex',
      requestPurpose: 'standard',
      clientModel: 'gpt-5.6-sol',
      effectiveModel: 'gpt-5.6-sol',
      upstreamModel: 'openai/gpt-5.6-sol',
      sourceFormat: 'openai-responses',
      targetFormat: 'openai-responses',
      routeMode: 'native',
      statusCode: 200,
      phase: 'completed',
      outcome: 'failed',
      ttfbMS: 410,
      durationMS: 2870,
      failover: false,
      featureRuleID: 'builtin-codex-primary',
      toolCalls: ['functions.exec_command', 'collaboration.spawn_agent'],
      codexMetadata: {
        threadID: 'thread-main-0001',
        agentName: '/root',
        turnID: 'turn-main-0041',
        windowID: 'thread-main-0001:6',
        requestKind: 'turn',
        originator: 'codex_cli_rs',
        sources: ['canonical_body'],
        malformed: false,
        truncated: false,
        hasConflicts: false,
        isSubagent: false,
        parentThreadIDInferred: false,
      },
      upstreamStatusCode: 200,
      upstreamRequestID: 'req_openai_failed_200_demo',
      failureKind: 'upstream_response_failed',
      failurePhase: 'response_stream',
      failureDetail: 'response.failed: server_error: The model encountered an error while processing the request',
      message: 'bridge openai-responses',
      streamTrace: {
        chunkCount: 19,
        bytesReceived: 6120,
        maxChunkGapMS: 340,
        lastChunkAtMS: 2860,
        terminalEvent: 'response.failed',
        usage: { inputTokens: 3200, outputTokens: 420 },
      },
    },
    {
      id: 'ev-websearch-1',
      requestID: 'req-ws-003',
      timestamp: now - 92000,
      kind: 'client',
      endpointID: 'ep-openrouter-fast',
      endpointName: 'OpenRouter 聚合加速',
      upstreamHost: 'openrouter.ai',
      clientKind: 'codex',
      requestPurpose: 'websearch',
      clientModel: 'claude-3-5-sonnet',
      effectiveModel: 'gpt-4o-mini',
      upstreamModel: 'gpt-4o-mini',
      statusCode: 200,
      phase: 'completed',
      outcome: 'succeeded',
      ttfbMS: 380,
      durationMS: 1240,
      failover: false,
      featureRuleID: 'rule-websearch',
      toolCalls: ['web_search'],
      codexMetadata: {
        installationID: 'sha256:demo-install',
        sessionID: 'session-demo-001',
        threadID: 'thread-demo-001',
        agentName: '/root/linux_final_tests',
        turnID: 'turn-demo-0042',
        windowID: 'thread-demo-001:7',
        requestKind: 'turn',
        forkedFromThreadID: 'thread-parent-0001',
        parentThreadID: 'thread-parent-0001',
        parentTurnID: 'turn-parent-0010',
        rootTurnID: 'turn-root-0001',
        subagentHeader: 'collab_spawn',
        subagentKind: 'thread_spawn',
        threadSource: 'collaboration',
        sandbox: 'workspace-write',
        sandboxMode: 'workspace-write',
        autoReviewEnabled: true,
        nodeReplAutoReviewRequired: false,
        nodeReplDisabled: false,
        turnStartedAtUnixMS: 1770000000000,
        originator: 'codex_cli_rs',
        betaFeatures: 'responses-2026-01',
        memgenRequest: 'disabled',
        responsesLite: 'false',
        wsStreamRequestStartMS: 1770000000123,
        workspaces: {
          '/workspace/demo': {
            associatedRemoteURLs: { origin: 'https://github.com/example/demo.git' },
            latestGitCommitHash: 'abc1234',
            hasChanges: true,
          },
        },
        toolNamespacesInfo: {
          functions: {
            name: 'functions',
            functions: {
              rg: {
                name: 'rg', direct: true, codeModeName: 'rg', deferred: false,
                source: { kind: 'built_in' },
              },
            },
          },
        },
        compaction: { trigger: 'threshold', reason: 'context', implementation: 'codex', phase: 'complete', strategy: 'summarize' },
        extras: { responses_api_metadata: 'demo' },
        sources: ['header', 'turn_metadata'],
        redactedFields: ['authorization'],
        conflicts: [],
        malformed: false,
        truncated: false,
        hasConflicts: false,
        isSubagent: true,
        parentThreadIDInferred: false,
      },
      streamTrace: {
        chunkCount: 36,
        bytesReceived: 8400,
        maxChunkGapMS: 90,
        lastChunkAtMS: 1210,
        terminalEvent: '[DONE]',
        usage: { inputTokens: 5100, outputTokens: 960 },
      },
      message: '命中 WebSearch 分流规则，已路由至 gpt-4o-mini',
    },
    {
      id: 'ev-cancel-499',
      requestID: 'req-cancel-004',
      timestamp: now - 180000,
      kind: 'client',
      endpointID: 'ep-anthropic-direct',
      endpointName: 'Anthropic 官方直连',
      upstreamHost: 'api.anthropic.com',
      clientKind: 'claude_code',
      requestPurpose: 'standard',
      clientModel: 'claude-3-5-sonnet',
      effectiveModel: 'claude-3-5-sonnet-20241022',
      upstreamModel: 'claude-3-5-sonnet-20241022',
      statusCode: 499,
      phase: 'completed',
      outcome: 'cancelled',
      ttfbMS: 450,
      durationMS: 2100,
      failover: false,
      failureKind: 'client_cancelled',
      failurePhase: 'response_stream',
      message: '客户端用户主动按下 Ctrl+C 取消请求 (499)',
    },
  ],
};

// Stable, completed SQLite history for exercising server-side pagination in
// the mock UI. Live in-flight rows deliberately remain only in `recentEvents`.
const mockCompletedEventTemplates = mockRuntime.recentEvents.filter((event) => event.phase === 'completed');
const mockProjectForEvent = (event, index) => {
  const projectName = event.codexMetadata?.workspaces ? 'automode-proxy'
    : event.id === 'ev-cancel-499' || index % 5 === 0 ? 'unidentified_project' : 'automode-proxy';
  return {
    projectID: `project-${projectName}`,
    projectName,
  };
};
export const mockRuntimeHistory = Array.from({ length: 137 }, (_, index) => {
  const template = mockCompletedEventTemplates[index % mockCompletedEventTemplates.length];
  const project = mockProjectForEvent(template, index);
  if (index < mockCompletedEventTemplates.length) return { ...template, ...project };
  const sequence = index + 1;
  return {
    ...template,
    ...project,
    id: `ev-history-${String(sequence).padStart(4, '0')}`,
    requestID: `req-history-${String(Math.floor(index / 2) + 1).padStart(4, '0')}`,
    timestamp: now - (sequence * 75_000),
    message: `${template.message || '历史事件'}（分页模拟 #${sequence}）`,
    codexMetadata: template.codexMetadata ? {
      ...template.codexMetadata,
      sessionID: `session-demo-${String((index % 8) + 1).padStart(3, '0')}`,
      threadID: `thread-demo-${String((index % 12) + 1).padStart(3, '0')}`,
    } : template.codexMetadata,
  };
});

// 与 Rust runtime_store 的 analytics wire 形状保持一致。入口行同时携带
// 端到端客户端 usage（由 requestID 归属到最终成功入口/最后一次尝试），
// 而 attempts/successes/failures 仍只来自 upstream 尝试，避免把 usage 当成
// 又一次请求计数。mock 页面因此可以直接验证“入口有 usage 且成功率守恒”。
export const mockAnalytics = {
  range: '24h',
  clientRequests: 1287,
  clientSuccesses: 1256,
  clientFailures: 28,
  clientCancelled: 3,
  clientPending: 0,
  clientSuccessRate: (1256 / (1256 + 28 + 3)) * 100,
  upstreamAttempts: 1390,
  upstreamSuccesses: 1260,
  upstreamFailures: 130,
  failovers: 42,
  averageDurationMS: 1250,
  averageTTFBMS: 420,
  latencyBuckets: { under1s: 6, from1sTo3s: 14, from3sTo6s: 4, over6s: 1 },
  endpoints: [
    {
      endpointID: 'ep-anthropic-direct', name: 'Anthropic 官方直连', attempts: 640, successes: 590, failures: 38, cancelled: 12, pending: 0,
      successRate: (590 / (590 + 38 + 12)) * 100, failovers: 16,
      averageDurationMS: 1120, averageTTFBMS: 380, eventIDs: [],
      inputTokens: 76000, outputTokens: 22000, cacheReadInputTokens: 60000,
      cacheCreationInputTokens: 5000, reasoningTokens: 5000, uncachedInputTokens: 76000,
      // Anthropic reports cache read/write independently from inputTokens;
      // processed input is therefore the non-overlapping sum (76k + 60k + 5k).
      processedInputTokens: 141000, processedTotalTokens: 163000, totalTokens: 98000, observedRequests: 55,
      usageFieldPresence: { inputTokens: 55, outputTokens: 55, cacheReadInputTokens: 55, cacheCreationInputTokens: 55, reasoningTokens: 12 },
      clientKinds: ['claude_code', 'codex'],
      tokenAccountingSemantics: 'independent', tokenAccountingQuality: 'complete',
    },
    {
      endpointID: 'ep-azure-eastus', name: 'Azure OpenAI 通道', attempts: 450, successes: 428, failures: 20, cancelled: 2, pending: 0,
      successRate: (428 / (428 + 20 + 2)) * 100, failovers: 18,
      averageDurationMS: 1380, averageTTFBMS: 460, eventIDs: [],
      inputTokens: 62000, outputTokens: 13600, cacheReadInputTokens: 41000,
      cacheCreationInputTokens: 3000, reasoningTokens: 3000, uncachedInputTokens: 18000,
      processedInputTokens: 62000, processedTotalTokens: 75600, totalTokens: 75600, observedRequests: 38,
      usageFieldPresence: { inputTokens: 38, outputTokens: 38, cacheReadInputTokens: 21, cacheCreationInputTokens: 3, reasoningTokens: 3 },
      clientKinds: ['openai_compat'],
      tokenAccountingSemantics: 'subset', tokenAccountingQuality: 'complete',
    },
    {
      endpointID: 'ep-openrouter-fast', name: 'OpenRouter 聚合加速', attempts: 300, successes: 242, failures: 58, cancelled: 0, pending: 0,
      successRate: (242 / (242 + 58)) * 100, failovers: 8,
      averageDurationMS: 1260, averageTTFBMS: 430, eventIDs: [],
      inputTokens: 44400, outputTokens: 13000, cacheReadInputTokens: 20000,
      cacheCreationInputTokens: 600, reasoningTokens: 1200, uncachedInputTokens: 23800,
      processedInputTokens: 44400, processedTotalTokens: 57400, totalTokens: 57400, observedRequests: 25,
      usageFieldPresence: { inputTokens: 25, outputTokens: 25, cacheReadInputTokens: 8, cacheCreationInputTokens: 1, reasoningTokens: 4 },
      clientKinds: ['openai_compat'],
      tokenAccountingSemantics: 'subset', tokenAccountingQuality: 'complete',
    },
  ],
  models: [
    {
      name: 'claude-opus-5', attempts: 684, successes: 658, failures: 22, cancelled: 4, pending: 0,
      inputTokens: 112000, outputTokens: 30200, cacheReadInputTokens: 76000, cacheCreationInputTokens: 5200,
      processedInputTokens: 112000, processedTotalTokens: 142200, observedRequests: 74,
      usageFieldPresence: { inputTokens: 74, outputTokens: 74, cacheReadInputTokens: 74, cacheCreationInputTokens: 41 },
      tokenAccountingSemantics: 'mixed', tokenAccountingQuality: 'complete',
      projectIDs: ['project-automode-proxy'], sessionIDs: ['session-demo-001'], endpointIDs: ['ep-anthropic-direct'],
    },
    {
      name: 'gpt-5.4', attempts: 312, successes: 298, failures: 13, cancelled: 1, pending: 0,
      inputTokens: 48400, outputTokens: 12600, cacheReadInputTokens: 31000, cacheCreationInputTokens: 2100,
      processedInputTokens: 48400, processedTotalTokens: 61000, observedRequests: 28,
      usageFieldPresence: { inputTokens: 28, outputTokens: 28, cacheReadInputTokens: 28, cacheCreationInputTokens: 17 },
      tokenAccountingSemantics: 'subset', tokenAccountingQuality: 'complete',
      projectIDs: ['project-automode-proxy', 'project-cc-declared-demo'], sessionIDs: ['session-demo-001'], endpointIDs: ['ep-azure-eastus', 'ep-openrouter-fast'],
    },
    {
      name: 'gpt-4o', attempts: 201, successes: 185, failures: 15, cancelled: 1, pending: 0,
      inputTokens: 22000, outputTokens: 5800, cacheReadInputTokens: 14000, cacheCreationInputTokens: 1300,
      processedInputTokens: 22000, processedTotalTokens: 27800, observedRequests: 16,
      usageFieldPresence: { inputTokens: 16, outputTokens: 16, cacheReadInputTokens: 16, cacheCreationInputTokens: 9 },
      tokenAccountingSemantics: 'subset', tokenAccountingQuality: 'complete',
      projectIDs: ['project-unidentified_project'], sessionIDs: ['unidentified_session'], endpointIDs: ['ep-azure-eastus'],
    },
  ],
  clientKinds: [],
  requestPurposes: [],
  featureRules: [],
  protocolRoutes: [],
  failureKinds: [],
  failurePhases: [],
  upstreamStatuses: [],
  streamTerminals: [],
  toolCalls: [],
  codexMetadataPresent: 0,
  tokenUsage: {
    inputTokens: 182400, outputTokens: 48600, cacheReadInputTokens: 121000,
    cacheCreationInputTokens: 8600, reasoningTokens: 9200, uncachedInputTokens: 117800,
    // Sum the per-endpoint normalized input totals (Anthropic is independent;
    // the two OpenAI-compatible endpoints use input as the cache-inclusive
    // subset denominator).
    processedInputTokens: 247400, processedTotalTokens: 296000, totalTokens: 231000,
    observedRequests: 118, tokenAccountingSemantics: 'mixed', tokenAccountingQuality: 'complete',
    cacheReadReportedRequests: 75, cacheReadHitRequests: 75,
    cacheReadTokenEligibleRequests: 75, cacheReadTokenUnknownRequests: 43,
    cacheReadTokenRate: 121000 / 247400, cacheReadRequestRate: 1,
    usageFieldPresence: { inputTokens: 118, outputTokens: 118, cacheReadInputTokens: 75, cacheCreationInputTokens: 48, reasoningTokens: 19 },
  },
  projects: [
    {
      name: 'automode-proxy', projectID: 'project-automode-proxy', attempts: 850, successes: 830, failures: 18, cancelled: 2, pending: 0,
      successRate: (830 / (830 + 18 + 2)) * 100, failovers: 30,
      averageDurationMS: 1100, averageTTFBMS: 360, eventIDs: [],
      inputTokens: 124000, outputTokens: 33000, cacheReadInputTokens: 84000,
      cacheCreationInputTokens: 4200, processedInputTokens: 124000, processedTotalTokens: 157000,
      totalTokens: 157000, observedRequests: 82,
      usageFieldPresence: { inputTokens: 82, outputTokens: 82, cacheReadInputTokens: 82, cacheCreationInputTokens: 34, reasoningTokens: 0 },
      clientKinds: ['claude_code', 'codex', 'openai_compat'], endpointIDs: ['ep-anthropic-direct', 'ep-openrouter-fast', 'ep-azure-eastus'], projectSource: 'workspace_local',
      tokenAccountingSemantics: 'mixed', tokenAccountingQuality: 'complete',
      eventIDs: ['ev-failover-client', 'ev-codex-response-failed-200'],
    },
    {
      name: 'cc-declared-demo', projectID: 'project-cc-declared-demo', attempts: 96, successes: 94, failures: 2, cancelled: 0, pending: 0,
      successRate: (94 / 96) * 100, failovers: 3,
      averageDurationMS: 980, averageTTFBMS: 300, eventIDs: [],
      inputTokens: 21000, outputTokens: 5400, cacheReadInputTokens: 12000,
      cacheCreationInputTokens: 900, processedInputTokens: 21000, processedTotalTokens: 26400,
      totalTokens: 26400, observedRequests: 24,
      usageFieldPresence: { inputTokens: 24, outputTokens: 24, cacheReadInputTokens: 24, cacheCreationInputTokens: 8, reasoningTokens: 0 },
      clientKinds: ['claude_code'], endpointIDs: ['ep-anthropic-direct'], projectSource: 'client_declared',
      tokenAccountingSemantics: 'subset', tokenAccountingQuality: 'complete',
      workspacePaths: ['.../.claude/cc-declared-demo'],
      eventIDs: ['ev-stream-live-1'],
    },
    {
      name: 'unidentified_project', projectID: 'project-unidentified_project', attempts: 437, successes: 426, failures: 10, cancelled: 1, pending: 0,
      successRate: (426 / (426 + 10 + 1)) * 100, failovers: 12,
      averageDurationMS: 1400, averageTTFBMS: 500, eventIDs: [],
      inputTokens: 58400, outputTokens: 15600, cacheReadInputTokens: 37000,
      cacheCreationInputTokens: 4400, processedInputTokens: 58400, processedTotalTokens: 74000,
      totalTokens: 74000, observedRequests: 36,
      usageFieldPresence: { inputTokens: 36, outputTokens: 36, cacheReadInputTokens: 36, cacheCreationInputTokens: 14, reasoningTokens: 0 },
      clientKinds: ['claude_code', 'openai_compat'], endpointIDs: ['ep-azure-eastus', 'ep-openrouter-fast'], projectSource: 'missing_workspace_metadata',
      tokenAccountingSemantics: 'mixed', tokenAccountingQuality: 'complete',
      eventIDs: ['ev-cancel-499'],
    },
  ],
  sessions: [
    {
      name: 'session-demo-001', projectIDs: ['project-automode-proxy'], attempts: 36, successes: 35, failures: 1, cancelled: 0, pending: 0,
      successRate: (35 / 36) * 100, failovers: 1, averageDurationMS: 1240, averageTTFBMS: 380, eventIDs: [],
      inputTokens: 58400, outputTokens: 15600, cacheReadInputTokens: 37000, cacheCreationInputTokens: 4400,
      processedInputTokens: 58400, processedTotalTokens: 74000, totalTokens: 74000, observedRequests: 36,
      usageFieldPresence: { inputTokens: 36, outputTokens: 36, cacheReadInputTokens: 36, cacheCreationInputTokens: 14, reasoningTokens: 0 },
      projects: ['automode-proxy'], clientKinds: ['codex'], endpointIDs: ['ep-anthropic-direct'], projectSource: 'workspace_local',
      tokenAccountingSemantics: 'subset', tokenAccountingQuality: 'complete',
      eventIDs: ['ev-websearch-1'],
    },
    {
      name: 'unidentified_session', projectIDs: ['project-automode-proxy', 'project-unidentified_project'], attempts: 1251, successes: 1221, failures: 27, cancelled: 3, pending: 0,
      successRate: (1221 / (1221 + 27 + 3)) * 100, failovers: 41, averageDurationMS: 1250, averageTTFBMS: 420, eventIDs: [],
      inputTokens: 0, outputTokens: 0, cacheReadInputTokens: 0, cacheCreationInputTokens: 0,
      processedInputTokens: 0, processedTotalTokens: 0, totalTokens: 0, observedRequests: 0,
      usageFieldPresence: { inputTokens: 0, outputTokens: 0, cacheReadInputTokens: 0, cacheCreationInputTokens: 0, reasoningTokens: 0 },
      projects: ['automode-proxy', 'unidentified_project'], clientKinds: ['claude_code', 'openai_compat'], endpointIDs: ['ep-azure-eastus', 'ep-openrouter-fast'], projectSource: 'missing_workspace_metadata',
      tokenAccountingSemantics: 'unknown', tokenAccountingQuality: 'unknown',
      eventIDs: ['ev-failover-client', 'ev-cancel-499'],
    },
  ],
  facets: {
    clientKinds: [
      { value: 'claude_code', count: 950 },
      { value: 'codex', count: 36 },
      { value: 'openai_compat', count: 301 },
    ],
    projects: [
      { value: 'automode-proxy', count: 850 },
      { value: 'unidentified_project', count: 437 },
    ],
    sessions: [
      { value: 'session-demo-001', count: 36 },
      { value: 'unidentified_session', count: 1251 },
    ],
    models: [
      { value: 'claude-opus-5', count: 684 },
      { value: 'gpt-5.4', count: 312 },
      { value: 'gpt-4o', count: 201 },
    ],
    requestPurposes: [
      { value: 'standard', count: 1032 },
      { value: 'websearch', count: 96 },
      { value: 'compact', count: 24 },
    ],
    failureKinds: [
      { value: 'upstream_response_failed', count: 18 },
      { value: 'stream_interrupted', count: 7 },
      { value: 'response_timeout', count: 4 },
    ],
    failurePhases: [
      { value: 'response_stream', count: 25 },
      { value: 'response_headers', count: 4 },
    ],
  },
};

export const mockDiagnostics = {
  version: '0.2.0',
  generation: 'gen-8f921bc3',
  uptimeSeconds: 14280,
  adminListener: { host: '127.0.0.1', port: 57879 },
  proxyListener: { host: '127.0.0.1', port: 57878 },
  statsWritable: true,
  configPath: '~/.config/sumpter/config.json',
  webRoot: '~/.local/share/sumpter/web',
  journalctlCommand: 'journalctl --user -u sumpter -n 200 --no-pager',
  warnings: [],
  capture: {
    enabled: false,
    startedAt: null,
    maxBytes: 512 * 1024 * 1024,
    capturedBytes: 512,
    limitReached: false,
    stopReason: null,
    recordCount: 1,
    indexTruncated: false,
    records: [{
      requestID: 'REQ-MOCK-001', timestamp: Date.now() / 1000 - 65, method: 'POST', path: '/v1/messages',
      clientKind: 'claude_code', requestPurpose: 'chat', clientModel: 'claude-opus-5', effectiveModel: 'claude-opus-5',
      featureRuleID: null, sourceFormat: 'anthropic', targetFormat: 'anthropic', routeMode: 'native',
      completedAtMS: 842, statusCode: 200, outcome: 'succeeded', failureKind: null, truncated: false,
      attemptCount: 1, clientChunkCount: 2,
    }],
  },
  captureDetails: {
    'REQ-MOCK-001': {
      requestID: 'REQ-MOCK-001', timestamp: Date.now() / 1000 - 65, method: 'POST', path: '/v1/messages',
      inboundHeaders: [{ name: 'content-type', value: 'application/json' }, { name: 'user-agent', value: 'claude-code/mock' }],
      inboundBody: '{"model":"claude-opus-5","messages":[{"role":"user","content":"diagnostic mock"}]}', inboundBodyBytes: 86, inboundBodyTruncated: false,
      clientKind: 'claude_code', requestPurpose: 'chat', clientModel: 'claude-opus-5', effectiveModel: 'claude-opus-5', featureRuleID: null,
      clientDeclared: { project: 'automode-proxy', workspace: '.../.claude/automode-proxy', gitRemote: 'https://github.com/domoxiaojun/sumpter.git' },
      sourceFormat: 'anthropic', targetFormat: 'anthropic', routeMode: 'native',
      attempts: [{ id: 'ATTEMPT-MOCK-001', endpointID: 'ep-mock', endpointName: 'Mock upstream', protocol: 'anthropic', pinnedIP: null, startedAtMS: 1,
        outboundMethod: 'POST', outboundURL: 'https://upstream.example/v1/messages', outboundHeaders: [{ name: 'content-type', value: 'application/json' }],
        outboundBody: '{"model":"claude-opus-5"}', outboundBodyBytes: 24, outboundBodyTruncated: false, responseStatus: 200,
        responseHeaders: [{ name: 'content-type', value: 'text/event-stream' }], upstreamChunks: [{ atMS: 400, bytes: 24, data: 'data: {"type":"message_stop"}\\n\\n', truncated: false }], error: null, completedAtMS: 840 }],
      clientChunks: [{ atMS: 842, bytes: 24, data: 'data: {"type":"message_stop"}\\n\\n', truncated: false }], completedAtMS: 842, statusCode: 200, outcome: 'succeeded', failureKind: null, failureDetail: null, truncated: false,
    },
  },
};

export const mockAutostart = {
  available: true,
  controllable: true,
  enabled: true,
  scope: 'user',
  unit: 'sumpter.service',
  reason: 'systemd user unit 已启用开机自启',
};
