[package]
name = "sumpter-engine"
edition.workspace = true
version.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[dependencies]
sumpter-core = { workspace = true }
sumpter-runtime = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
axum = { workspace = true }
hyper = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
futures-util = { workspace = true }
base64 = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
md-5 = { workspace = true }
sha2 = { workspace = true }
argon2 = { workspace = true }
async-trait = { workspace = true }
tokio-util = { workspace = true }
tower-http = { workspace = true }
rusqlite = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }
sumpter-core = { workspace = true }
